CREATE DATABASE EMPLOYS;
USE EMPLOYS;

CREATE TABLE EMPLOYEE(
EMP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
EMP_NAME VARCHAR(32),
SALARY INT
);

INSERT INTO EMPLOYEE VALUE(101,'MOHAN',40000),
(DEFAULT,'JAMES',50000),
(DEFAULT,'ROHAN',60000),
(DEFAULT,'CARLO',70000),
(DEFAULT,'ALICE',80000),
(DEFAULT,'JENNY',90000);

SELECT * FROM EMPLOYEE;

WITH AVERAGE_SALARY (AVG_SAL) AS
	(SELECT  AVG(SALARY)  FROM EMPLOYEE)
SELECT * 
FROM EMPLOYEE E , AVERAGE_SALARY AV
WHERE E.SALARY>AV.AVG_SAL;
    


WITH AVERAGE_SALARY (AVG_SAL) AS
	(SELECT  CAST(AVG(SALARY) AS INT)  FROM EMPLOYEE)
SELECT * 
FROM EMPLOYEE E , AVERAGE_SALARY AV
WHERE E.SALARY>AV.AVG_SAL;


-- SELECT * FROM EMPLOYEE E,AVERAGE_SALARY WHERE E.SALARY >AVERAGE_SALARY.AVG_SALARY;



WITH TOTAL_SALES (STORE_ID,TOTAL_SALES_PER_STORE) AS
	(SELECT S.STORE_ID,SUM(COST) AS TOTAL_SALES_PER_STORE
	FROM SALES S
	GROUP BY S.STORE_ID),
    
    AVG_SALES(AVG_SALES_FOR_ALL_STORES) AS
    (SELECT AVG(TOTAL_SALES_PER_STORE) AS AVG_SALES_FOR_ALL_STORES
    FROM TOTAL_SALES)
    
SELECT * 
FROM TOTAL_SALES TS
JOIN AVG_sALES AV
ON TS.TOTAL_SALES_PER_STORE>AV.AVG_SALES_FOR_ALL_STORES;


-- LIMIT AND OFFSET
SELECT * FROM EMPLOYEE WHERE SALARY>50000 LIMIT 3 OFFSET 1;




SELECT * FROM PEOPLE WHERE
(FIRST_NAME='AARON' AND ID>25995)
ORDER BY FIRST_NAME , ID
LIMIT 10;